HubSpot/ui-extensions-examples

- display-iframe/src/app/crm-card.json
- success-and-error-banners/src/app/crm-card.json
The build now throws an error when `propertiesToSend` is not provided, so this PR explicitly sets `propertiesToSend` to an empty array.
```
[ERROR] There was an error parsing the JSON for the file `crm-card.json`. error = `object has missing required properties (["propertiesToSend"])`
```
> fix: Set propertiesToSend to empty array to prevent new validation error

- .eslintrc.js
- README.md
- display-iframe/src/app/app.functions/crm-card.js
- package-lock.json
- package.json
- success-and-error-banners/src/app/app.functions/action-feedback-banner.js
- success-and-error-banners/src/app/app.functions/crm-card.js
This PR sets up ESLint at the root of this repository using the `eslint:recommends` rule set. Some short documentation on what ESLint is and how to use it is included in the README. And, lastly, this PR also fixes the 3 infractions of the `no-unused-vars` rule.
The key is that using ESLint is not a required part of interacting with this repository, but it can create a nicer development experience for those that choose to use it, and this configuration can serve as an example within itself on how to use this sort of tooling for developer projects.
Prettier next 🤞
> chore: Set up ESLint

- include-npm-dependencies/.gitignore
- include-npm-dependencies/README.md
- include-npm-dependencies/hsproject.json
- include-npm-dependencies/src/app/app.functions/crm-card.js
- include-npm-dependencies/src/app/app.functions/package-lock.json
- include-npm-dependencies/src/app/app.functions/package.json
- include-npm-dependencies/src/app/app.functions/serverless.json
- include-npm-dependencies/src/app/app.json
- include-npm-dependencies/src/app/crm-card.json
This PR introduces a new example to demonstrate how to include and use npm dependencies for a custom CRM card, using `day.js` as an example. The README for the project (included in this PR) has more information and instructions for use.
> feat(include-npm-dependencies): Add example for using npm dependencies

- .eslintrc.js
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATES/bug_report.md
- .prettierignore
- .prettierrc.json
- README.md
- display-iframe/README.md
- display-iframe/src/app/app.functions/crm-card.js
- display-iframe/src/app/app.json
- include-npm-dependencies/README.md
- include-npm-dependencies/src/app/app.functions/crm-card.js
- include-npm-dependencies/src/app/app.json
- package-lock.json
- package.json
- success-and-error-banners/README.md
- success-and-error-banners/src/app/app.functions/action-feedback-banner.js
- success-and-error-banners/src/app/app.functions/crm-card.js
- success-and-error-banners/src/app/app.json
This PR sets up Prettier for this repository, includes [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier#installation) to prevent collisions between ESLint and Prettier, and runs the existing files through it (excluding the generated LICENSE.md file and the other files that are by default excluded by Prettier, like anything in `node_modules/`). It also adds a brief explanation of Prettier and how to use it if one so chooses to the README.
> chore: Set up Prettier

- simple-form/.gitignore
- simple-form/README.md
- simple-form/hsproject.json
- simple-form/src/app/app.functions/crm-card.js
- simple-form/src/app/app.functions/serverless.json
- simple-form/src/app/app.json
- simple-form/src/app/crm-card.json
Displays a simple form with a text input and a submit button that, when pressed, passes the form data to the serverless function through the `context.event.payload.formState` and displays the user inputted data in a banner.
> feat(simple-form): Create example of a simple form

- display-iframe/src/app/app.functions/serverless.json
- include-npm-dependencies/src/app/app.functions/serverless.json
- simple-form/src/app/app.functions/serverless.json
- success-and-error-banners/src/app/app.functions/serverless.json
Since AWS has [announced end of support for `nodejs12.x`](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) starting in May 2023, we're updating our examples to use `nodejs16.x`.
These examples should continue to function as-is.
> Update examples to use Node 16.x

- contact-duplicate/src/app/extensions/.eslintrc
- contact-duplicate/src/app/extensions/Extension.tsx
- contact-duplicate/src/app/extensions/package.json
Test of integrating [`@hubspot/eslint-config-ui-extensions`](https://www.npmjs.com/package/@hubspot/eslint-config-ui-extensions) package to provide better linting support for examples.
> feat: Add eslint support for contact-duplicate example

- with-crm-components/src/app/app.functions/updateDeal.js
The QA api was being used for testing but was missed in PR review. Update to be pointing at the correct prod api.
> [with-crm-components] Switch serverless function to use prod api

- contact-duplicate/package.json
- example-meal-order/package.json
- with-crm-components/package.json
Running an `npm install` from the project root was causing a syntax error in powershell because `npm install;` was parsed as `npm` and `install;`, so `npm` would rightfully error saying `install;` is not a valid command.
> fix: Remove ; from post-install to support powershell

- flex-and-box/package.json
- flex-and-box/src/app/extensions/package.json
Removing `@hubspot/cli` as a local dependency because we need it to be installed globally on the system
> chore: Remove `@hubspot/cli` as a dep since it will be installed globally

- company-proximity-navigator/src/app/app.functions/getCompaniesWithDistanceBatch.js
- company-proximity-navigator/src/app/extensions/NearestCompanies.jsx
- company-proximity-navigator/src/app/extensions/TopValueCompanies.jsx
- contact-duplicate/src/app/extensions/Extension.tsx
- deals-summary/src/app/extensions/DealsSummary.jsx
- example-meal-order/src/app/extensions/OrderMealExtension.tsx
- example-meal-order/src/app/extensions/components/OrderMealCard.tsx
- example-meal-order/src/app/extensions/types.ts
- quote-generator/src/app/app.functions/createQuote.js
- quote-generator/src/app/extensions/ShuttleBusQuotes.jsx
- with-crm-components/src/app/extensions/StageTrackerExtension.tsx
* We are introducing a simpler API, `hubspot.serverless`, for calling app functions in `@hubspot/ui-extensions@0.8.5`.
* Note that the `runServerlessFunction` way still works. 
* See [an example](https://github.com/HubSpot/ui-extensions-examples/pull/49/commits/ed4e332c87fd311bde583b48adb09bdaf01021cb) migrating from `runServerlessFunction` to `hubspot.serverless`.
_This PR is best reviewed by commits._
With promise syntax:
```javascript
import { hubspot } from "@hubspot/ui-extensions";
hubspot.extend(() => <Extension />);
const Extension = () => {
const handleSubmit = () => {
hubspot
.serverless("func-name", {
// options, if any (e.g., propertiesToSend or parameters)
})
.then((response) => {
// handle response, which is the value returned from the function on success
})
.catch((error) => …
```
> feat: Update examples to use new API for calling app functions

- mapbox-api/src/app/app.functions/getCompaniesWithDistanceBatch.js
- mapbox-api/src/app/extensions/SearchNeardlyCompanies.jsx
- mapbox-api/src/app/extensions/components/CompaniesWithDistanceTable.jsx
Omit a company in calculating distance if no address specified.
When no address is specified for the current company record:
> Handle error when no company address is specified

- duplicate-contact/src/app/app.functions/duplicateContact.js
To avoid exceptions when duplicating contacts with readonly properties, we remove this property `hubspotscore`[(issue)](https://github.com/HubSpot/ui-extensions-examples/issues/77). Additionally, we remove the non-existent property `photo`.
> remove readonly and not existing properties

- bi-directional-property-refresh/src/app/extensions/PropertyRefreshExtension.tsx
- crm-data-components/src/app/extensions/StageTrackerExtension.tsx
- deals-summary/src/app/extensions/DealsSummaryExampleCard.jsx
- duplicate-contact/src/app/extensions/Extension.tsx
- generate-quotes/src/app/extensions/GenerateMultipleQuotesExampleCard.jsx
- mapbox-api/src/app/extensions/CompaniesNearTheCurrentRecord.jsx
- mapbox-api/src/app/extensions/SearchNeardlyCompanies.jsx
- multi-step-flow/src/app/extensions/OrderMealExtension.tsx
- multi-step-flow/src/app/extensions/components/OrderMealCard.tsx
- multi-step-flow/src/app/extensions/types.ts
_This change was previously introduced in #49 then reverted in #59, because we did not have product rollout lined up. I'm submitting this change again to finish the swing. We are hoping to have the examples updated and the API officially documented by the end of the month._
* We are introducing a simpler API, `hubspot.serverless`, for calling app functions in `@hubspot/ui-extensions@0.8.5`.
* Note that the `runServerlessFunction` way still works. 
* See [an example](https://github.com/HubSpot/ui-extensions-examples/pull/49/commits/ed4e332c87fd311bde583b48adb09bdaf01021cb) migrating from `runServerlessFunction` to `hubspot.serverless`.
_This PR is best reviewed by commits._
With promise syntax:
```javascript
import { hubspot } from "@hubspot/ui-extensions";
hubspot.extend(() => <Extension …
```
> feat: Update examples to use `hubspot.serverless` for calling app functions

- design-patterns/.gitignore
- design-patterns/README.md
- design-patterns/hsproject.json
- design-patterns/src/app/app.json
- design-patterns/src/app/extensions/FormActionPatterns.tsx
- design-patterns/src/app/extensions/FormModal.tsx
- design-patterns/src/app/extensions/FormMultistep.tsx
- design-patterns/src/app/extensions/form-action-patterns.json
- design-patterns/src/app/extensions/form-modal.json
- design-patterns/src/app/extensions/form-multistep.json
- design-patterns/src/app/extensions/package.json
This PR adds a new app to showcase design patterns, aka composed sets of components ready to copy and paste into projects. This initial phase of work includes three `Form` component patterns.
**Modal Form**
**Form Action Patterns**
**Multistep Form**
> feat: Add design patterns app with initial Form examples

- design-patterns/README.md
- design-patterns/src/app/extensions/FormModal.tsx
- design-patterns/src/app/extensions/FormMultistep.tsx
I updated the copy in the form design patterns to be more clear about what we are communicating.
I also did some re-arranging of the Readme links, to make the patterns easier to link to each component via JS Docs
> Updated form copy & readme example links

- crm-data-components/src/app/extensions/package.json
- display-iframe-modal/src/app/extensions/package.json
I noticed some old references to `@hubspot/ui-extensions-dev-server` in a couple projects, and wanted to remove them to prevent any confusion.
All projects should be using `hs project dev` for local developement, so these projects must have been built before that was finalized.
> chore: Remove references to old ui-extensions-dev-server

- design-patterns/src/app/extensions/Table.jsx
Following up from Design Patterns doc sync, add column of buttons in Table Example
Uploaded changes to `Design Patterns` card in `ui-extensibility` hublet in prod to check out. 
**updated screenshot** of uploaded changes to `Design Patterns` card:
> [design-patterns]: add action button column in Table Example

- config.json
We want the design patterns app to be available as a template for `hs project create`, so I added it to the config. This allows this command to work:
```
hs project create --templateSource="HubSpot/ui-extensions-examples" --dest="design-patterns" --name="design-patterns" --template="design-patterns"
```
> fix: Add design patterns to template list

- config.json
- data-table/LICENSE.md
- data-table/README.md
- data-table/hsproject.json
- data-table/src/app/extensions/DataTable.tsx
- data-table/src/app/extensions/data-table.json
- data-table/src/app/extensions/package.json
- data-table/src/app/public-app.json
This is a new example to demonstrate how to build a table which displays data from an external API. It shows how to use pagination, as well as demonstrates a good loading state.
> feat: Add new Data Table example
